import Link from "next/link";
import { LegalDocumentShell } from "@/components/legal-document-shell";
import { LegalH2 } from "@/components/legal-h2";
import { LegalIntro } from "@/components/legal-intro";
import { pageMetadata, siteConfig } from "@/lib/site";

export const metadata = pageMetadata({
  title: "Privacy Policy",
  path: "/privacy-policy",
  description:
    "Docfyle Advisory privacy policy: how we collect, use, disclose, and protect your information when you use our website and services.",
});

const privacyToc = [
  { id: "interpretation-and-definitions", label: "Interpretation and Definitions", shortLabel: "Definitions" },
  {
    id: "collecting-and-using-your-personal-data",
    label: "Collecting and Using Your Personal Data",
    shortLabel: "Data collection",
  },
  { id: "use-of-your-personal-data", label: "Use of Your Personal Data", shortLabel: "How we use data" },
  { id: "retention-of-your-personal-data", label: "Retention of Your Personal Data", shortLabel: "Retention" },
  { id: "transfer-of-your-personal-data", label: "Transfer of Your Personal Data", shortLabel: "Transfers" },
  { id: "delete-your-personal-data", label: "Delete Your Personal Data", shortLabel: "Deletion" },
  { id: "disclosure-of-your-personal-data", label: "Disclosure of Your Personal Data", shortLabel: "Disclosure" },
  { id: "security-of-your-personal-data", label: "Security of Your Personal Data", shortLabel: "Security" },
  { id: "childrens-privacy", label: "Children's Privacy", shortLabel: "Children" },
  { id: "links-to-other-websites", label: "Links to Other Websites", shortLabel: "External links" },
  { id: "changes-to-this-privacy-policy", label: "Changes to This Privacy Policy", shortLabel: "Updates" },
  { id: "contact-us", label: "Contact Us", shortLabel: "Contact" },
];

export default function PrivacyPolicyPage() {
  return (
    <LegalDocumentShell
      eyebrow="Privacy"
      subtitle="Docfyle Advisory — Bookkeeping & Accounting Services (USA). How we handle your information and your privacy rights."
      title="Privacy Policy"
      toc={privacyToc}
    >
      <LegalIntro>
        This Privacy Policy describes our policies and procedures on the collection, use, and disclosure of your
        information when you use the Service and explains your privacy rights and how the law protects you. We use your
        personal data to provide and improve the Service. By using the Service, you agree to the collection and use of
        information in accordance with this Privacy Policy.
      </LegalIntro>

      <LegalH2 id="interpretation-and-definitions">Interpretation and Definitions</LegalH2>
      <h3>Interpretation</h3>
      <p>
        Words with an initial capital letter have specific meanings defined below. These definitions apply whether they
        appear in singular or plural.
      </p>

      <h3>Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul>
        <li>
          <strong>Account</strong> means a unique account created for you to access our Service or parts of it.
        </li>
        <li>
          <strong>Affiliate</strong> means any entity that controls, is controlled by, or is under common control with a
          party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest, or voting rights.
        </li>
        <li>
          <strong>Company</strong> (referred to as &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot;, or
          &quot;Our&quot;) refers to Docfyle Advisory Private Limited, 6203 San Ignacio Avenue, Suite 110, San Jose, CA
          95119, United States.
        </li>
        <li>
          <strong>Cookies</strong> are small files placed on your computer, mobile device, or other device by a website,
          containing details of your browsing history and preferences among other uses.
        </li>
        <li>
          <strong>Country</strong> refers to the United States and India, where applicable to our operations.
        </li>
        <li>
          <strong>Device</strong> means any device that can access the Service, such as a computer, mobile phone, or
          tablet.
        </li>
        <li>
          <strong>Personal Data</strong> means any information relating to an identified or identifiable individual.
        </li>
        <li>
          <strong>Service</strong> refers to the Website and related offerings described on our site.
        </li>
        <li>
          <strong>Service Provider</strong> means any natural or legal person who processes data on behalf of the Company
          (for example, hosting, analytics, or email delivery vendors).
        </li>
        <li>
          <strong>Usage Data</strong> refers to data collected automatically, generated by use of the Service or its
          infrastructure (for example, duration of a page visit).
        </li>
        <li>
          <strong>Website</strong> refers to Docfyle Advisory, accessible from{" "}
          <Link href="https://docfyleadvisory.com">https://docfyleadvisory.com</Link>.
        </li>
        <li>
          <strong>You</strong> means the individual accessing or using the Service, or the company or other legal entity
          on behalf of which such individual accesses or uses the Service, as applicable.
        </li>
      </ul>

      <LegalH2 id="collecting-and-using-your-personal-data">Collecting and Using Your Personal Data</LegalH2>
      <h3>Types of Data Collected</h3>
      <h3>Personal Data</h3>
      <p>
        While using our Service, we may ask you to provide certain personally identifiable information that can be used
        to contact or identify you. This may include, but is not limited to:
      </p>
      <ul>
        <li>Email address</li>
        <li>First and last name</li>
        <li>Phone number</li>
        <li>Address, state, province, ZIP/postal code, and city</li>
        <li>Business or organization information</li>
      </ul>

      <h3>Usage Data</h3>
      <p>Usage Data is collected automatically and may include information such as:</p>
      <ul>
        <li>Internet Protocol (IP) address</li>
        <li>Browser type and version</li>
        <li>Pages of our Service that you visit</li>
        <li>Time and date of your visit</li>
        <li>Time spent on those pages</li>
        <li>Device identifiers and diagnostic data</li>
      </ul>
      <p>
        If you access the Service on a mobile device, we may collect certain information automatically, including the
        type of mobile device, unique device identifiers, mobile operating system, and mobile browser type.
      </p>

      <h3>Tracking Technologies and Cookies</h3>
      <p>
        We use Cookies and similar tracking technologies to track activity on our Service and store certain information.
        Technologies we use may include:
      </p>
      <ul>
        <li>
          <strong>Cookies or browser cookies</strong>
        </li>
        <li>
          <strong>Web beacons</strong> (small files embedded in emails or pages to record engagement)
        </li>
      </ul>
      <p>
        Cookies may be <strong>session</strong> (deleted when you close your browser) or{" "}
        <strong>persistent</strong> (remain on your device for a set period or until deleted).
      </p>
      <p>Types of cookies we may use include:</p>
      <ul>
        <li>
          <strong>Necessary / essential cookies</strong> (often session) — enable core functionality and security.
        </li>
        <li>
          <strong>Cookie policy / notice acceptance cookies</strong> (often persistent) — record your consent where
          required.
        </li>
        <li>
          <strong>Functionality cookies</strong> (often persistent) — remember preferences and settings.
        </li>
      </ul>
      <p>
        For more detail on cookies and your choices, please refer to our Cookies Policy if posted on the Website, or
        contact us using the details below.
      </p>

      <LegalH2 id="use-of-your-personal-data">Use of Your Personal Data</LegalH2>
      <p>The Company may use Personal Data for purposes such as:</p>
      <ul>
        <li>To provide and maintain our Service</li>
        <li>To manage your Account and registration</li>
        <li>To perform a contract with you</li>
        <li>To contact you by email, telephone, SMS, or other reasonable communication methods</li>
        <li>
          To provide news, updates, and information about our services (where permitted and subject to your marketing
          preferences)
        </li>
        <li>To manage and respond to your requests</li>
        <li>
          In connection with a business transfer, such as a merger, acquisition, or sale of assets (with appropriate
          notice where required)
        </li>
        <li>For analysis, understanding usage, improving our Service, and measuring marketing effectiveness</li>
      </ul>
      <p>We may share your information in situations such as:</p>
      <ul>
        <li>With Service Providers who assist us in operating the Service</li>
        <li>With Affiliates, subject to this Policy</li>
        <li>In connection with a business transfer</li>
        <li>With business partners where you have agreed or as described at collection</li>
        <li>With other users when you choose to share information in public areas of the Service</li>
        <li>With your consent or at your direction</li>
      </ul>

      <LegalH2 id="retention-of-your-personal-data">Retention of Your Personal Data</LegalH2>
      <p>
        We retain Personal Data only for as long as necessary for the purposes set out in this Privacy Policy, to comply
        with legal obligations, resolve disputes, and enforce our agreements.
      </p>

      <LegalH2 id="transfer-of-your-personal-data">Transfer of Your Personal Data</LegalH2>
      <p>
        Your information may be processed and stored in jurisdictions other than your own. If we transfer Personal Data
        across borders, we take steps designed to ensure appropriate safeguards where required by applicable law. By
        using the Service, you understand that such transfers may occur.
      </p>

      <LegalH2 id="delete-your-personal-data">Delete Your Personal Data</LegalH2>
      <p>
        You may request deletion of Personal Data we hold about you, where applicable law allows. You may do this through
        your account settings (if available) or by contacting us. We may retain certain information where we have a legal
        right or obligation to do so.
      </p>

      <LegalH2 id="disclosure-of-your-personal-data">Disclosure of Your Personal Data</LegalH2>
      <p>
        <strong>Business transactions:</strong> Personal Data may be transferred if the Company is involved in a merger,
        acquisition, or asset sale. We will provide notice before your Personal Data is transferred and becomes subject
        to a different policy, where required.
      </p>
      <p>
        <strong>Law enforcement:</strong> Under certain circumstances, we may disclose Personal Data if required by law
        or in response to valid requests by public authorities.
      </p>
      <p>
        <strong>Other legal requirements:</strong> We may disclose Personal Data in the good-faith belief that such
        action is necessary to comply with a legal obligation, protect our rights or property, prevent wrongdoing, protect
        personal safety, or protect against legal liability.
      </p>

      <LegalH2 id="security-of-your-personal-data">Security of Your Personal Data</LegalH2>
      <p>
        We use commercially reasonable safeguards designed to protect your Personal Data. No method of transmission over
        the Internet or electronic storage is completely secure, and we cannot guarantee absolute security.
      </p>

      <LegalH2 id="childrens-privacy">Children&apos;s Privacy</LegalH2>
      <p>
        Our Service is not directed to individuals under 13 (or the minimum age required in your jurisdiction). We do
        not knowingly collect Personal Data from children. If you believe we have collected such information, please
        contact us and we will take steps to delete it promptly where required.
      </p>

      <LegalH2 id="links-to-other-websites">Links to Other Websites</LegalH2>
      <p>
        Our Service may contain links to third-party websites. We are not responsible for the privacy practices or content
        of those sites. We encourage you to read the privacy policy of every site you visit.
      </p>

      <LegalH2 id="changes-to-this-privacy-policy">Changes to This Privacy Policy</LegalH2>
      <p>
        We may update this Privacy Policy from time to time. We will post the updated Policy on this page and may notify
        you by email or a prominent notice on the Service if changes are material, where required by law.
      </p>

      <LegalH2 id="contact-us">Contact Us</LegalH2>
      <p>If you have questions about this Privacy Policy, contact us:</p>
      <ul>
        <li>
          By email: <a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a>
        </li>
        <li>
          By visiting our website: <Link href="https://docfyleadvisory.com">https://docfyleadvisory.com</Link>
        </li>
      </ul>
    </LegalDocumentShell>
  );
}
